### ISSUE TITLE
Fatal error: Uncaught Error: Undefined constant "XOOPS_CONF_USER"

### ISSUE THREAD

**Issue by tikyon** [jegelstaff/formulize#337]
This happens on "Import Data" window from List screen.

> Fatal error: Uncaught Error: Undefined constant "XOOPS_CONF_USER" in /modules/formulize/include/import.php on line 68

I tried commenting it out and the page is able to load and complete the import successfully.

**Comment by jegelstaff** [comment]
Thank you. Fixed in 29af42342

**Comment by tikyon** [comment]
Hi Julian,

It appears you need the quotes or the fatal error will still occur. So, it should be `defined('XOOPS_CONF_USER')` for the condition on line 68.

**Comment by jegelstaff** [comment]
Ack! Absolutely right. I'll get that.
